### ISSUE TITLE
state not matched

### ISSUE THREAD

**Issue by tanwiz13** [xcarpentier/react-native-linkedin#101]
#### Issue Description

{"type": "state_not_matched","message":"state is not the same ............................"}

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* Expo version: [FILL THIS OUT]
* react-native-linkedin version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by muhammadmisbah** [comment]
did you get the solution for this?

**Comment by LinuiLeaf** [comment]
I got the same issue. I added redirectUri as "http://localhost:3000/" then the issue went off.Now it's working fine.
