### ISSUE TITLE
Adding custom style to button

### ISSUE THREAD

**Issue by rawsly** [xcarpentier/react-native-linkedin#102]
#### Issue Description

I was looking around if there is a feature to add custom style to linkedin button?

#### Steps to Reproduce / Code Snippets

render() method inside index.js uses TouchableOpacity component. However, it doesn't have "style" prop inside it and also the library doesn't have style prop inside it. I tried to wrap LinkedInModal with TouchableOpacity but I couldn't handle onPress method so that it calls LinkedInModal's onSuccess prop.

#### Expected Results

Custom LinkedInModal styling.

#### Additional Information

* Nodejs version: v8.10.0
* React version: 16.2.0
* React Native version: 0.52.0
* react-native-linkedin version: 1.3.1
* Platform(s) (iOS, Android, or both?): both

**Comment by eminsr** [comment]
You can add a custom button with renderButton prop. 

Place these lines inside render function just before return.
```
const renderButton = () => {
      return (
        <Button
             onPress={() => this.modal.open()}
             title="Learn More"
             color="#841584"
             accessibilityLabel="Learn more about this purple button"
         />
      );
    };
```

And add these lines to your LinkedInModal component.

```
      ref={ref => {
                    this.modal = ref;
                  }}
      renderButton={renderButton}
```

**Comment by rawsly** [comment]
> You can add a custom button with renderButton prop.
> 
> Place these lines inside render function just before return.
> 
> ```
> const renderButton = () => {
>       return (
>         <Button
>              onPress={() => this.modal.open()}
>              title="Learn More"
>              color="#841584"
>              accessibilityLabel="Learn more about this purple button"
>          />
>       );
>     };
> ```
> And add these lines to your LinkedInModal component.
> 
> ```
>       ref={ref => { this.modal = ref; }}
>       renderButton={renderButton}
> ```

Hi,
I actually know that I can use ref attribute to achieve this but what I was trying to say that why there is no feature about "styling" in LinkedInModal render method. Because it is using TouchableOpacity inside render function of LinkedInModal. Therefore it should be easy to add this prop also. For example, I added that prop manually inside library, however it was just testing purpose and I know that it is not practical to alter library :)

Thanks for your reply anyway. :)

**Comment by nonstuff** [comment]
> You can add a custom button with renderButton prop.
> 
> Place these lines inside render function just before return.
> 
> ```
> const renderButton = () => {
>       return (
>         <Button
>              onPress={() => this.modal.open()}
>              title="Learn More"
>              color="#841584"
>              accessibilityLabel="Learn more about this purple button"
>          />
>       );
>     };
> ```
> 
> And add these lines to your LinkedInModal component.
> 
> ```
>       ref={ref => { this.modal = ref; }}
>       renderButton={renderButton}
> ```

its not this.modal.open() ==> wrong
its this.modal.current.open() ===> correct

**Comment by dzilva** [comment]
not working.

TypeError: undefined is not an object (evaluating '_this.modal = _ref')

how can i fix this?

**Comment by Android-Dheeraj** [comment]
@dzilva 
Define model inside your component
 linkedRef = React.createRef();
 <LinkedInModal
                          ref={this.linkedRef}
                            shouldGetAccessToken={true}
                                clientID={'your client ID'}
                                clientSecret={'your secret ID'}
                                redirectUri={'https://www.google.com/'}
                                linkText="Continue"
                                onError={async (error)=>{
                                    //console.log("tapak","fefef")
                                }}
                                onClose={async ()=>{
                                }}
                                onSuccess={async (token)  => {
                                    const data = token.access_token
                                  await  this.setState({
                                        showLinkedIn:false,
                                        linkedInAccessToken:data
                                    })
                                    this.getLinkedInUser()
                                    console.log("AAAA",this.state.linkedInAccessToken)
                                }}
                                containerStyle={{backgroundColor:'#2E92CC'}}
                            />
