### ISSUE TITLE
how to get user email id?

### ISSUE THREAD

**Issue by Jainrock999** [xcarpentier/react-native-linkedin#103]
I am getting user basic profile  by 'https://api.linkedin.com/v1/people/' but how can i get user email id ?

**Comment by eminsr** [comment]
Default permission array of the library is **['r_basicprofile', 'r_emailaddress']** so you probably just need to change your **Default Application Permissions** settings in LinkedIn developer console like below.

![screen shot 2018-10-10 at 19 26 22](https://user-images.githubusercontent.com/15310365/46751182-6f6df900-ccc2-11e8-9a52-5bd2a31f92dd.png)

**Comment by Jainrock999** [comment]
![screen shot 2018-10-11 at 2 37 24 pm](https://user-images.githubusercontent.com/38749323/46793407-46ea0b80-cd63-11e8-8724-41becf8727f8.png)
