### ISSUE TITLE
onSuccess or onSignIn is not fired on Android the first time user authentication is successful

### ISSUE THREAD

**Issue by AkshitSahani** [xcarpentier/react-native-linkedin#108]
#### Issue Description

On newer Android devices, the onSuccess and onSignIn methods are not fired when the authentication is successful the first time. But next time you tap on the button, the modal doesnt show up (modalVisible is set to false since the authentication keys are present in browser cache) and the methods are fired.

#### Steps to Reproduce / Code Snippets

- Trigger the WebView modal on an Android device.
- Put in correct LinkedIn user information in the modal and click on "Sign In".
- The modal stays open and the browser simply redirects to the redirect URI (google.com in my case since the redirection doesn't matter), without the onSuccess or onSignIn methods being fired. (I placed logs in both of the methods and don't see any logs).
- Close the modal via the X on the top right. Press the button to trigger the modal again.
-This time, the modal doesnt show, but both the methods are fired.

#### Expected Results

- Even the first time user authentication is successful, the onSuccess and onSignIn methods should be fired on Android. It works exactly like that in iOS. The firing of the methods is required to successfully log in/sign up the user. But on Android, the modal window stays and the browser within it just redirects to the redirect URI. The user has to manually close the modal and re-tap on the button to have the methods fired and result in log in/sign up.

#### Additional Information

* Nodejs version: N/A
* React version: 16.3.1
* React Native version: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz
* Expo version: ^28.0.0
* react-native-linkedin version: ^1.3.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by tranhiepqna** [comment]
Could you please share me your solution for this issue? Thank you

**Comment by AkshitSahani** [comment]
@tranhiepqna I haven't found a solution for this yet. I am waiting for @xcarpentier to provide some help with this.
