### ISSUE TITLE
webView is not opened for the second time login

### ISSUE THREAD

**Issue by dcpliot** [xcarpentier/react-native-linkedin#109]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* Expo version: [FILL THIS OUT]
* react-native-linkedin version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by cidevant** [comment]
Clear cookies (react-native-cookies)
