### ISSUE TITLE
Can't able to login with different account

### ISSUE THREAD

**Issue by dcpliot** [xcarpentier/react-native-linkedin#110]
#### Issue Description

[I used this plugin in my project and such that I was able to login and directed to other screen.Now I killed the app and opened from the begining like login screen opened,in that if I press login button,I didn't see any WebView to enter mailId and password,directly directed to other screen.Now my question is ,suppose I want to login with different inkedin account,how to achieve it?]

#### Steps to Reproduce / Code Snippets

[ render(){
return(
  
            <LinkedInModal
                ref={ref => {
                  this.modal = ref
                }}
          clientID="81a16hxcmazz9u"
          clientSecret="2RCPbA247Heoln6C"
          redirectUri="https://xaviercarpentier.com"
          onSuccess={(token) => {
            // await AsyncStorage.setItem('access_token',token);
            console.log("getting token",token);
    
              this.getLinkedInUser(token)
         
          }}
          onCancel={(data)=>{
            // console.log("onClose",JSON.stringify(data))
            alert('LinkedIn Login is Cancelled');
            // this.props.navigation.navigate('LoginScreen');
          }}
          onError={(error)=>{
                        console.log("onError",JSON.stringify(error))
                        alert('LinkedIn Login is Cancelled ');

          }}
          linkText={null}
        
        />
  
      <TouchableOpacity style={styles.LinkedInStyle} activeOpacity={0.5} onPress={()=>{
          console.log("linkedin login is  first time",this.state.linkedInFirstTime);
          // this.props.storeData(" " , "linkedin");
          this.modal.open((data)=>{
          console.log("opening freshly",JSON.stringify(data1));
          })
        }
        }>
        <Image
         source={require('./../../assets/linkedin.png')}
         style={styles.ImageIconStyle}
         />

        <View style={styles.SeparatorLine} />

        <Text style={styles.TextStyle}>Login Using LinkedIn </Text>
      </TouchableOpacity>)
}

 getLinkedInUser=async ({ access_token })=> {
  try{
   console.log("inside getLinkedInUser",access_token ) ;
  this.setState({ refreshing: true })
  const baseApi = 'https://api.linkedin.com/v1/people/'
  const qs = { format: 'json' }
  const params = [
    'first-name',
    'last-name',
    'picture-urls::(original)',
    'headline',
    'email-address',
    'id'
  ]
  // const token=await AsyncStorage.setItem('access_token',access_token);

 fetch(`${baseApi}~:(${params.join(',')})?format=json`, {
    method: 'GET',
    headers: {
      Authorization: 'Bearer ' + access_token,
    },
  })
  .then(async (response)=>response.json())
  .then(async (payload)=>{
    console.log("inside payload");
     this.props.storeData(payload , "linkedin");
  })
  .catch((error)=>{
    console.log("error while fetching",JSON.stringify(error.message));
  })
  
}
catch(error){
  console.log("error",error.message);
}
}
]

#### Expected Results

[When I kill the app,and opens again and clicks on the login button,I should again get the WebView for entering details at some conditions]

#### Additional Information

* Nodejs version: [v8.11.4]
* React version: [FILL THIS OUT]
* React Native version: [0.57]
* Expo version: [FILL THIS OUT]
* react-native-linkedin version: [^1.3.1]
* Platform(s) (iOS, Android, or both?): [both]

**Comment by cidevant** [comment]
I used `react-native-cookies`: 

```
import CookieManager from 'react-native-cookies';
CookieManager.clearAll();
```

**Comment by dcpliot** [comment]
Thanks for your response..Even I used the same,then got it work

**Comment by mainakCbnits** [comment]
Can't clear cookies in expo SDK 36. Can anyone plz help me?
