### ISSUE TITLE
Possible incompatibility with RN 0.58.x

### ISSUE THREAD

**Issue by mCodex** [xcarpentier/react-native-linkedin#113]
#### Issue Description

Hi, first of all thanks for this awesome library. I was facing an issue implementing RNLinkedin in my project and I've seen an error in RN 0.58.4 regarding new version of react-native's Modal.

Check out the error:

![simulator screen shot - iphone 7 - 2019-02-13 at 16 34 26](https://user-images.githubusercontent.com/5920613/52734813-41206300-2fad-11e9-88ea-c8d9bb02bda9.png)

#### Steps to Reproduce / Code Snippets

Installing RNLinkedin in a project using RN 0.58.4 using:

```javascript
<LinkedInModal
          clientID="[ Your client id from https://www.linkedin.com/developer/apps ]"
          clientSecret="[ Your client secret from https://www.linkedin.com/developer/apps ]"
          redirectUri="[ Your redirect uri set into https://www.linkedin.com/developer/apps ]"
          onSuccess={token => console.log(token)}
        />
```

#### Suggested Solution

I couldn't find any documentation about Modal's proptypes, although I was able to fix it by changing this line: https://github.com/xcarpentier/react-native-linkedin/blob/master/index.js#L211 to:

```javascript
  static propTypes = {
    ...,
    animationType: PropTypes.string,
    ...
  }
```

If it is okay, I could open a PR to fix it for you :)

* Nodejs version: 11.2.0
* React version: 16.3.3
* React Native version: 058.4
* Expo version: I don't use Expo
* react-native-linkedin version: 1.3.1
* Platform(s) (iOS, Android, or both?): Both

**Comment by xcarpentier** [comment]
Thanks,
Are you able to create a PR with the fix?

**Comment by mCodex** [comment]
Done! 🎉

**Comment by ploxhire** [comment]
When will this be merged? I lost quite a few hours figuring out that it was coming from react-native-linkedin. 

"Cannot read property 'animationType' of undefined". 

Any version of RN >= 0.58 is not compatible with this library due to this.

**Comment by martin-badin** [comment]
hello please, create new release
