### ISSUE TITLE
LinkedIn v1 to v2 API Migration 

### ISSUE THREAD

**Issue by nirpeled** [xcarpentier/react-native-linkedin#116]
#### Issue Description

LI  made some changes to their API - does this require any changes?

https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context

**Comment by paour** [comment]
The v2 API changes the `scopes` that you can request, and the API to access the data (it's become even more annoyingly obtuse), but the OAuth process hasn't changed. I've migrated to the new API without needing to update this module.

**Comment by nirpeled** [comment]
Yeah - same for me, I made changes to the scope object and everything works, thanks!

**Comment by muhammadmisbah** [comment]
how? can you give any exampe?

**Comment by paour** [comment]
> how? can you give any exampe?

Read the link above, it describes the changes in the scopes parameter.

**Comment by nirpeled** [comment]
@muhammadmisbah 
```js
<LinkedInModal
    clientID={clientID}
    clientSecret={clientSecret}
    redirectUri={redirectUri}
    onSuccess={this.onSuccess}
    renderButton={() => <Button />}
    permissions={['r_liteprofile', 'r_emailaddress']}
    animationType={`slide`}
    onOpen={this.onOpen}
/>
```

**Comment by muhammadmisbah** [comment]
@nirpeled Thanks, i appreciate that. I did the same but when I click the button model open and gets closed in a second, onError function I'was getting JSON {type: state_not_match, message: state is not the same undefined}

Then I thought there can be something wrong with app creation on LinkedIn, I deleted the previous app from the LinkedIn dashboard and created another one, and put those client and secret id. Now I'm getting this JSON onError function {type: invalid_request, message: A required parameter \"code\" is missing}..

I have been stuck for 3 days in this, LinkedIn doesn't have proper documentation.. they changed somethin.

**Comment by nirpeled** [comment]
@muhammadmisbah We didn't make any changes to our app on LinkedIn - check out their docs on this, perhaps you're passing or not passing an important param

**Comment by muhammadmisbah** [comment]
![image](https://user-images.githubusercontent.com/20583580/54879757-924e2d00-4e5e-11e9-9d23-b8b209cd3656.png)
What does the state mean? what will it compare with? why is it required? what should be the value and where do i put the value?

And,
In this library it gets authState. ref: https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L49

and it's comparing with state. ref: https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L153
and I'm getting state undefined

**Comment by muhammadmisbah** [comment]
> @muhammadmisbah We didn't make any changes to our app on LinkedIn - check out their docs on this, perhaps you're passing or not passing an important param

I put the redirect Url on LinkedIn App settings, now it's getting the same previous state error.. 

> ![image](https://user-images.githubusercontent.com/20583580/54879757-924e2d00-4e5e-11e9-9d23-b8b209cd3656.png)
> What does the state mean? what will it compare with? why is it required? what should be the value and where do i put the value?
> 
> And,
> In this library it gets authState. ref:
> 
> [react-native-linkedin/index.js](https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L49)
> 
> Line 49 in [d18157e](/xcarpentier/react-native-linkedin/commit/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b)
> 
>  authState?: string, 
> and it's comparing with state. ref:
> 
> [react-native-linkedin/index.js](https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L153)
> 
> Line 153 in [d18157e](/xcarpentier/react-native-linkedin/commit/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b)
> 
>  } else if (state !== authState) { 
> 
> [react-native-linkedin/index.js](https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L154)
> 
> Line 154 in [d18157e](/xcarpentier/react-native-linkedin/commit/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b)
> 
>  onError({ 
> 
> [react-native-linkedin/index.js](https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L155)
> 
> Line 155 in [d18157e](/xcarpentier/react-native-linkedin/commit/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b)
> 
>  type: 'state_not_match', 
> 
> [react-native-linkedin/index.js](https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L156)
> 
> Line 156 in [d18157e](/xcarpentier/react-native-linkedin/commit/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b)
> 
>  message: `state is not the same ${state}`, 
> 
> and I'm getting state undefined, and this condition is being run for me, i don't know why..
> I had done instagram, facebook & google authentication with SDK and as well as on web, I didn't face anything like this.

**Comment by muhammadmisbah** [comment]
I've solved this all, I don't know what was the happened there was some linkedIn issue, I just created one more app on LinkedIn dashboard and linked that app, that app was getting run as it should have been.

**Comment by tanwiz13** [comment]
> The v2 API changes the `scopes` that you can request, and the API to access the data (it's become even more annoyingly obtuse), but the OAuth process hasn't changed. I've migrated to the new API without needing to update this module.

First of all, thanks for the update. Can you please tell us whether the entire functionality ( i.e. login and profile fetching ) works fine after migrating to the v2 APIs? Also, can you please upload your working code as a reference?

**Comment by paour** [comment]
Look at [this comment](https://github.com/xcarpentier/react-native-linkedin/issues/116#issuecomment-475918536).

**Comment by muhammadmisbah** [comment]
@tanwiz13
There was only authorization with LinkedIn in this library, and the webview still appears after authorization and go to the redirectUrl, we can do deep linking but I thought there is no need.. 
I just copied the js file of this library and customized it with my own way what i needed, (email, name, profilePicture etc.)
I put everything in onNavigationChange method, I made my repo public you can see here: https://github.com/muhammadmisbah/LinkedInAuth/blob/afe3ef43027597939ddde93e52efb5498ebb943f/src/containers/LinkedInView/index.js#L317

**Comment by muhammadmisbah** [comment]
@tanwiz13 
You can clone the repo, put your credentials in App.js and check, this repo is just for signing in with LinkedIn.
https://github.com/muhammadmisbah/LinkedInAuth.git

**Comment by Prat041192** [comment]
> ```js
> permissions={['r_liteprofile', 'r_emailaddress']}
> ```

Hi @nirpeled 
I tried sending the permissions the way you have mentioned ( via LinkedInModal props), But I am still getting 403 from the server 
`{ serviceErrorCode: 100,
      message: 'Not enough permissions to access: GET /people/~:(email-address)',
      status: 403 }`
Could you please help me here?

**Comment by muhammadmisbah** [comment]
@Prat041192 
here is the example video, what you need https://drive.google.com/open?id=1sXeKVvXY-pnuF8v0wdTJJx_OwDaXCClI
here is the code of this example: 
https://github.com/muhammadmisbah/LinkedInAuth.git
I modified the library to get ['r_liteprofile', 'r_emailaddress'];

I faced too much issues to implement this library and i also had to made another app on LinkedIn console, the first was getting error, I couldn't find the reason but the new one was working fine.

**Comment by Prat041192** [comment]
> 
> 
> @Prat041192
> here is the example video, what you need https://drive.google.com/open?id=1sXeKVvXY-pnuF8v0wdTJJx_OwDaXCClI
> here is the code of this example:
> https://github.com/muhammadmisbah/LinkedInAuth.git
> I modified the library to get ['r_liteprofile', 'r_emailaddress'];
> 
> I faced too much issues to implement this library and i also had to made another app on LinkedIn console, the first was getting error, I couldn't find the reason but the new one was working fine.

Thanks @muhammadmisbah  I was able to solve my problem.
