### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.Modal.propTypes.animationType')

### ISSUE THREAD

**Issue by Sudarshan101** [xcarpentier/react-native-linkedin#122]
> undefined is not an object (evaluating '_reactNative.Modal.propTypes.animationType')
> <unknown>
>     index.cjs.js:2374:70
> loadModuleImplementation
>     require.js:331:6
> <unknown>
>     Use.js:29:4
> loadModuleImplementation
>     require.js:331:6
> <unknown>
>     
> loadModuleImplementation
>     require.js:331:6
> <unknown>
>     ReactFabric-prod.js:5442:8
> loadModuleImplementation
>     require.js:331:6
> <unknown>
>     index.js:7
> loadModuleImplementation
>     require.js:331:6
> guardedLoadModule
>     require.js:197:45
> global code
    
Anyone please provide me solution.

**Comment by karthikajjan** [comment]
I am also facing same issue

> undefined is not an object (evaluating '_reactNative.Modal.propTypes.animationType')
...\node_modules\react-native-linkedin\index.js:211:35

**Comment by ruben2807** [comment]
Same issue, could someone solve it?

**Comment by maulikdhameliya** [comment]
This issue is already fixed in latest master code
@ruben2807 @karthikajjan @Sudarshan101 
so to use latest code use following in `package.json`

```"react-native-linkedin": "git+https://github.com/xcarpentier/react-native-linkedin.git",```

**Comment by maulikdhameliya** [comment]
@xcarpentier can you release the new version of the library and close this issue

**Comment by xcarpentier** [comment]
fix on 1.3.2
