### ISSUE TITLE
How to expire session?

### ISSUE THREAD

**Issue by NooruddinLakhani** [xcarpentier/react-native-linkedin#125]
#### Issue Description
I am using this library but the issue is when I first signIn, it asks me for email and password then i successfully get user detail and logged in but when i delete account in app and again signIn, it's not asking me email and password again, it stored the last login session and using it for login without asking credentials again 

#### Expected Results

Every time I login through linkedin, it should always ask for email and password.

**Comment by xcarpentier** [comment]
you have to use api to logout

**Comment by NooruddinLakhani** [comment]
@xcarpentier  can you please suggest api or provide a link ?

**Comment by SnehalRam** [comment]
@xcarpentier Hi, how to logout ?

**Comment by neoketan** [comment]
@NooruddinLakhani have found any solution?please share if you have

**Comment by Gjoshi3107** [comment]
@neoketan your link is not working.
can you check and upload it again

**Comment by neoketan** [comment]
@Gjoshi3107 just checked it is working
if you try it on browser it will redirect to login screen and if you have any active session, it will be closed

**Comment by xcarpentier** [comment]
Able to logout on `2.1.0`
https://github.com/xcarpentier/react-native-linkedin/blob/master/App.tsx#L118
