### ISSUE TITLE
message: "This resource is no longer available under v1 APIs"

### ISSUE THREAD

**Issue by adybuciuman** [xcarpentier/react-native-linkedin#127]
#### Issue Description

I used the example how to get basic profile of a user after getting the token and this is the reponse from my request.

#### Steps to Reproduce / Code Snippets

```
const baseApi = 'https://api.linkedin.com/v1/people/'
const params = [
  'first-name',
  'last-name',
  // add more fields here
]

 handleLinkedInToken = async (token: any) => {
    const response = await fetch(
      `${baseApi}~:(${params.join(',')})?format=json`,
      {
        method: 'GET',
        headers: {
          Authorization: 'Bearer ' + token.access_token
        }
      }
    )
    const payload = await response.json()
  }
```
##### Result

![image](https://user-images.githubusercontent.com/12176091/59681024-8fec3c80-91db-11e9-85e8-109bf530667b.png)

#### Alternative

I tried with v2,  but is not working.

#### Additional Information

* React version: "16.6.3"
* React Native version: "^0.59.5"
* react-native-linkedin version: "^1.3.2"

**Comment by jose2007kj** [comment]
[check here](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context)
