### ISSUE TITLE
Query:  Why ramda is used?

### ISSUE THREAD

**Issue by saikiranoptisol** [xcarpentier/react-native-linkedin#129]
I have a doubt why ramda component is used in this library. why is it used and what is the use of it in other developments. Just a query to know, so that i can get use of this ramda components in my projects if i find it useful.

**Comment by neoketan** [comment]
Ramda https://ramdajs.com/
Useful links - https://codeburst.io/currying-in-javascript-ba51eb9778dc

Specifically designed for functional programming
The primary distinguishing features of Ramda are:
* Ramda emphasizes a purer functional style. Immutability and side-effect free functions are at the heart of its design philosophy. This can help you get the job done with simple, elegant code. 
* Ramda functions are automatically curried. This allows you to easily build up new functions from old ones simply by not supplying the final parameters. 
* The parameters to Ramda functions are arranged to make it convenient for currying. The data to be operated on is generally supplied last. 
The last two points together make it very easy to build functions as sequences of simpler functions, each of which transforms the data and passes it along to the next. Ramda is designed to support this style of coding.


Ramda

1) pipe
http://randycoulman.com/blog/2016/05/31/thinking-in-ramda-combining-functions/

Ramda provides the pipe function, which takes a list of one or more functions and returns a new function.
The new function takes the same number of arguments as the first function it is given. It then “pipes” those arguments through each function in the list. It applies the first function to the arguments, passes its result to the second function and so on. The result of the last function is the result of the pipe call.
e.g.

function addition(a,b){
  return a+b
}

function display(result){
  console.log(result)
}

var myfun=R.pipe(addition,display);

myfun(11,2)


2) applySpec
const getMetrics = R.applySpec({
  sum: R.add,
  nested: { mul: R.multiply }
});
getMetrics(2, 4); // => { sum: 6, nested: { mul: 8 } }

3) props and propsOr
const alice = {
  name: 'ALICE',
  age: 101
};
const favorite = R.prop('favoriteLibrary');
const favoriteWithDefault = R.propOr('Ramda', 'age');

favorite(alice);  //=> undefined //there no key favoriteLibrary
favoriteWithDefault(alice);  //=> // 101

4) evolve
Creates a new object by recursively evolving a shallow copy of object, according to the transformation functions. All non-primitive properties are copied by reference.
