### ISSUE TITLE
[Question] Why this library render the open button?

### ISSUE THREAD

**Issue by slestang** [xcarpentier/react-native-linkedin#13]
It seems to me that it should be out of the scope of this library to takes care of rendering the open button.
I think it make more sense that the component act more like a controlled component and therefore receive an "open" prop that the user should take care to set at false when required (auth is finished).

In my case, I need a "Login with LinkedIn" button that check if the LinkedIn app is installed and if its the case use the Mobile SDK for login, otherwise use this project to log with a webview (the full workflow is a little bit more complicated).
Because I need to show the webview programmatically, I cannot use your library in its current state.

What do you think?

**Comment by xcarpentier** [comment]
Hello @slestang,
Thank you for your feedback.

I will add a props for that issue you have.

If you need your own button Style you should use renderButton props to provide it.

**Comment by xcarpentier** [comment]
Actually I make an example to open the modal from the outside of the component via ref.
You can find it here: 
- https://github.com/xcarpentier/react-native-linkedin/blob/master/example/App.js#L33
- https://github.com/xcarpentier/react-native-linkedin/blob/master/example/App.js#L52
