### ISSUE TITLE
 WebView has been removed from React Native.

### ISSUE THREAD

**Issue by ZishanK** [xcarpentier/react-native-linkedin#132]
#### Issue Description

Invariant Violation: WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'.

#### Steps to Reproduce / Code Snippets

<LinkedInModal
          clientID="***********"
          clientSecret="***********"
          redirectUri="*************"
          onSuccess={token => console.log(token)}
        />
#### Expected Results

Linkedin Login Screen

#### Additional Information

* Nodejs version: v12.9.1
* React version: 16.8.6
* React Native version: 0.60.5
* react-native-linkedin version: ^1.3.2
* Platform(s) (iOS, Android, or both?): both

**Comment by xcarpentier** [comment]
fixed with `v2.0.3`
