### ISSUE TITLE
Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by sregg** [xcarpentier/react-native-linkedin#134]
#### Issue Description

I'm already depending on `react-native-webview` and when I updated to today's `2.1.0` of `react-native-linkedin` I'm getting this error:

```
Tried to register two views with the same name RNCWebView
```

I've tried to use the same version of `react-native-webview` which is 7.0.5 and I'm getting the same error.

I've tried to remove it from my `package.json` and I'm getting this error:

```
Unable to resolve module `react-native-webview`
```

#### Additional Information

* Nodejs version: 10.16.3
* React version: 16.8.6
* React Native version: 0.60.5
* react-native-linkedin version: 2.10
* Platform(s) (iOS, Android, or both?): iOS
* react-native-webview version: 7.0.5

**Comment by xcarpentier** [comment]
Maybe try to remove node_modules first and start clearing rn cache...

**Comment by sregg** [comment]
All good after `npm cache clean --force`
