### ISSUE TITLE
componentWillUpdate() renamed Warning

### ISSUE THREAD

**Issue by MTayyabMehar** [xcarpentier/react-native-linkedin#135]
#### Issue Description
==>node_modules\react-native\Libraries\Core\setUpDeveloperTools.js:73
**Warning:** componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: LinkedInModal

#### Additional Information

* Nodejs version: [v10.13.0]
* react-native-cli: [2.0.1]
* react-native: [0.61.2]
* react-native-linkedin version: [2.1.0]
* Platform(s) (iOS, Android, or both?): [Android currently]

**Comment by xcarpentier** [comment]
see `2.2.1`

**Comment by MTayyabMehar** [comment]
Thanks

**Comment by Malikkhoja** [comment]
Even we are facing the same warning. The latest release version is 2.1.0 and not 2.2.1. 

Am we missing something here?
