### ISSUE TITLE
cant get email address / profile picture / headline 

### ISSUE THREAD

**Issue by tasad-7** [xcarpentier/react-native-linkedin#139]
import React from 'react'
import {
  StyleSheet,
  View,
  Text,
  Button,
  ActivityIndicator,
  StatusBar,
} from 'react-native'
import LinkedInModal from 'react-native-linkedin';

const styles = StyleSheet.create({
  container: {
    flex: 1,   
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shade: {
    overlayColor: 'linear-gradient(to bottom right, red, yellow)',
     opacity: .65,
     position: 'absolute',
     top: 0,
     left: 0,
     right: 0,
     bottom: 0,
     zIndex: 1
   },
   gradientstyle: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 900,
    zIndex: 2,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0
  },
  userContainer: {
    width: '100%',
    padding: 10,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  picture: {
    width: 200,
    height: 200,
    borderRadius: 100,
    resizeMode: 'cover',
    marginBottom: 15,
  },
  item: {
    width: '100%',
    flexDirection: 'row',
    marginVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  label: {
    marginRight: 10,
  },
  value: {
    fontWeight: 'bold',
    marginLeft: 10,
  },
  linkedInContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  labelContainer: {
    alignItems: 'flex-end',
  },
  valueContainer: {
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
})

export default class Linkedin extends React.Component {
  state = {
    access_token: undefined,
    expires_in: undefined,
    refreshing: false,
    localizedFirstName: undefined,
    localizedLastName: undefined,
    id: undefined,
    headline: undefined,
    emailaddress: undefined,
    profilePicture: undefined,
  }

  modal = React.createRef()

  constructor(props) {
    super(props)
    StatusBar.setHidden(true)
  }

  getUser = async (data) => {
    const { access_token, authentication_code } = data
    if (!authentication_code) {
      this.setState({ refreshing: true })

      const response = await fetch('https://api.linkedin.com/v2/me', {
        method: 'GET',
        headers: {
          Authorization: 'Bearer ' + access_token,
        },
      })
      const payload = await response.json()
      this.setState({ ...payload, refreshing: false })
    } else {
      alert(`authentication_code = ${authentication_code}`)
    }
  }

  renderItem(label, value) {
    return value ? (
      <View style={styles.item}>
        <View style={styles.labelContainer}>
          <Text style={styles.label}>{label}</Text>
        </View>
        <Text>👉</Text>
        <View style={styles.valueContainer}>
          <Text style={styles.value}>{value}</Text>
        </View>
      </View>
    ) : null
  }

  signOut = () => {
    this.setState({ refreshing: true })
    this.modal.current
      .logoutAsync()
      .then(() =>
        this.setState({ localizedLastName: undefined, localizedFirstName: undefined, id: undefined, refreshing: false }),
      )
  }

  render() {
    const { refreshing, localizedFirstName, localizedLastName, id } = this.state
    return (
      <View style={styles.container}>
        <View style={styles.linkedInContainer}>
          <LinkedInModal
            ref={this.modal}
            clientID="@@@@@@@@"
            clientSecret="@@@@@@@@"
            redirectUri="@@@@@@@@"
            onSuccess={this.getUser}
            
          />
        </View>

        {refreshing && <ActivityIndicator size="large" />}

        {localizedLastName, localizedFirstName, id && (
          <>
            <View style={styles.userContainer}>
              
              {this.renderItem('First name', localizedFirstName)}
              {this.renderItem('Last name', localizedLastName)}
              {this.renderItem('ID', id)}
              
            </View>
            <Button title="Log Out" onPress={this.signOut} />
          </>
        )}
      </View>
    )
  }
}

**Comment by mensonones** [comment]
how I get the data. The endpoint of email is different...

```javascript
 const instance = axios.create({
      baseURL: 'https://api.linkedin.com/v2',
      headers: {
        Authorization: 'Bearer ' + token,
      },
    });
    await Promise.all([
      instance.get('/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))'),
      instance.get('/clientAwareMemberHandles?q=members&projection=(elements*(primary,type,handle~))'),
    ])
```

**Comment by tasad-7** [comment]
Thanks, can you show me how you are displaying name, id, profile picture ?

**Comment by tasad-7** [comment]
@mensonones

**Comment by mensonones** [comment]
Here's a simple example using React Hooks

```javascript
import React, { useState, useEffect } from "react";
import { StyleSheet, View, Text, Image } from "react-native";
import axios from "axios";

import LinkedInModal from "react-native-linkedin";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center"
  }
});

export default function App() {
  const [token, setToken] = useState("");
  const [info, setInfo] = useState();
  const [loading, setLoading] = useState(true);

  const instance = axios.create({
    baseURL: "https://api.linkedin.com/v2",
    headers: {
      Authorization: "Bearer " + token
    }
  });

  async function getInfo() {
    await instance
      .get(
        "/me?projection=(id,firstName,lastName,profilePicture(displayImage~:playableStreams))"
      )
      .then(response => {
        setInfo(response.data);
        setLoading(false);
      })
      .catch(error => console.log(error));
  }

  useEffect(() => {
    getInfo();
  }, [token]);

  const renderData = info && (
    <>
      <Text>{info.firstName.localized.pt_BR}</Text>
      <Text>{info.lastName.localized.pt_BR}</Text>
      <Image
        source={{
          uri:
            info.profilePicture["displayImage~"].elements[3]["identifiers"][0][
              "identifier"
            ]
        }}
        style={{
          width: 200,
          height: 200,
          left: "auto",
          right: "auto",
          justifyContent: "center"
        }}
      />
    </>
  );

  return (
    <View style={styles.container}>
      <LinkedInModal
        clientID="**********"
        clientSecret="*******"
        redirectUri="**********"
        onSuccess={token => setToken(token.access_token)}
        onError={error => console.log(error)}
        areaTouchText={{top: 20, bottom: 20, left: 150, right: 150}}
      />
      {loading && <Text>{"Loading..."}</Text>}
      {renderData}
    </View>
  );
}
```

**Comment by tasad-7** [comment]
@mensonones Hey so for the same code can you guide me through the logout functionality, thanks

**Comment by mensonones** [comment]
@tasad-7 , I'm using info Linkedin for added user in firebase, and after this, i use only firebase for management user logged. Try this solution: https://stackoverflow.com/questions/58968159/how-do-i-clear-a-session-or-logout-using-the-linkedin-rest-api
