### ISSUE TITLE
How to access logoutAsync on other screen?

### ISSUE THREAD

**Issue by nonstuff** [xcarpentier/react-native-linkedin#140]

**Comment by xcarpentier** [comment]
https://github.com/xcarpentier/react-native-linkedin/blob/master/README.md#how-to-logout-react-native-linkedin

**Comment by nonstuff** [comment]
> https://github.com/xcarpentier/react-native-linkedin/blob/master/README.md#how-to-logout-react-native-linkedin

how to access logoutAsync on other screen?? #140

how to logout from other screen ???
is there any way to get LOGOUTASYNC() on other component?

**Comment by xcarpentier** [comment]
You have to do it yourself for now or make a PR :)

**Comment by xcarpentier** [comment]
https://github.com/xcarpentier/react-native-linkedin/blob/master/src/index.tsx#L403

**Comment by xcarpentier** [comment]
To logout, you have to open a web view with the logout URL.

**Comment by nonstuff** [comment]
> To logout, you have to open a web view with the logout URL.

thank you its done.
