### ISSUE TITLE
How to logout from linkedin usign react-native-linkedin? 

### ISSUE THREAD

**Issue by LudinaReema** [xcarpentier/react-native-linkedin#142]
Hi,

I am able to successfully login to linkedin. Once the login credentials are put and after getting the access token, if I go back to do the same with the other login credentials it won't ask for the input fields to enter the credentials. It provides directly the access token of the previous one. How to overcome this issue?

I tried to logout, but I am not able to find the props of this.linkedRef.current.logoutAsync();

Is there any way to solve these issues?

**Comment by pwketankulkarni** [comment]
check How to expire session? #125

**Comment by nonstuff** [comment]
> Hi,
> 
> I am able to successfully login to linkedin. Once the login credentials are put and after getting the access token, if I go back to do the same with the other login credentials it won't ask for the input fields to enter the credentials. It provides directly the access token of the previous one. How to overcome this issue?
> 
> I tried to logout, but I am not able to find the props of this.linkedRef.current.logoutAsync();
> 
> Is there any way to solve these issues?

I already created this issue but not getting respond yet...

**Comment by xcarpentier** [comment]
https://github.com/xcarpentier/react-native-linkedin/blob/master/README.md#how-to-logout-react-native-linkedin
