### ISSUE TITLE
renderButton isn't work

### ISSUE THREAD

**Issue by joaoguilhermee** [xcarpentier/react-native-linkedin#143]
#### Issue Description

The renderButton props isn't work corretly. I'm put a Icon and is render only the icon whitout the TouchableOpacity. 
In the source is corretly, but in the node_module folder are wrong.

**git hub source**
`if (renderButton) {
      return(
        <TouchableOpacity  
        accessibilityComponentType={'button'}
        accessibilityTraits={['button']}
        onPress={this.open}
        hitSlop={areaTouchText} 
        disabled={isDisabled}>
          {renderButton()}
        </TouchableOpacity>
      )
    }`

**node_module folder:**

`if (renderButton) {
                return renderButton();
            }`

#### Steps to Reproduce / Code Snippets
My code:
`
 <LinkedInModal
              shouldGetAccessToken={false}
              clientSecret={null}
              clientID="xxxx"
              redirectUri="http://example.com"
              onSuccess={({authentication_code}) =>
             {}              }
              renderButton={() => (
                <>
                  <IconLinkedin />
                </>
              )}
            />
`

#### Expected Results
I expect the custom render inside the button.

#### Additional Information

* Nodejs version: v12.7.0
* React version: 16.9.0
* React Native version: 0.60.5
* Expo version: no expo
* react-native-linkedin version: ^2.1.1
* Platform(s) (iOS, Android, or both?): both

**Comment by mensonones** [comment]
Hi, @joaoguilhermee . Example how i used the lib with icon.

```javascript
return (
    <TouchableOpacity style={styles.buttonLoginLinkedin}>
      <View style={{left: 10}}>
        <IconFont name="linkedin" size={20} color="#fff" />
      </View>
      <Text style={styles.textBtnLoginLinkedin}> {'Continuar com'} </Text>
      <LinkedInModal
        linkText={textBtn}
        clientID={clientIdLinkedin}
        clientSecret={clientSecretLinkedin}
        redirectUri="https://api.linkedin.com/v2/me"
        onSuccess={token => setToken(token.access_token)}
        onError={error => console.log(error)}
        areaTouchText={{top: 20, bottom: 20, left: 150, right: 200}}
      />
    </TouchableOpacity>
  );
```

**Comment by danielco56** [comment]
You can do something like I did here with the ref

**Comment by dzilva** [comment]
> ```js
> linkText={textBtn}
> ```

Hi,
Can i apply a <Text>Text Text</Text> to the linkText={textBtn}
Please if can I appreciate your help.
Thanks!

**Comment by dzilva** [comment]
> Hi, @joaoguilhermee . Example how i used the lib with icon.
> 
> ```js
> return (
>     <TouchableOpacity style={styles.buttonLoginLinkedin}>
>       <View style={{left: 10}}>
>         <IconFont name="linkedin" size={20} color="#fff" />
>       </View>
>       <Text style={styles.textBtnLoginLinkedin}> {'Continuar com'} </Text>
>       <LinkedInModal
>         linkText={textBtn}
>         clientID={clientIdLinkedin}
>         clientSecret={clientSecretLinkedin}
>         redirectUri="https://api.linkedin.com/v2/me"
>         onSuccess={token => setToken(token.access_token)}
>         onError={error => console.log(error)}
>         areaTouchText={{top: 20, bottom: 20, left: 150, right: 200}}
>       />
>     </TouchableOpacity>
>   );
> ```

Hi,
Can i apply a Text Text to the linkText={textBtn}
Please if can I appreciate your help.
Thanks!
