### ISSUE TITLE
onSuccess not called on Android

### ISSUE THREAD

**Issue by patrikwork1** [xcarpentier/react-native-linkedin#144]
#### Issue Description

Hi, the package is working fine on iOS but on Android the onSuccess method is not called after a login.

#### Steps to Reproduce / Code Snippets

onSuccess={data => console.log(data))

#### Expected Results

onSuccess is called and returns data. (iOS works fine, Android is not working)

#### Additional Information

* React version: 16.8.3
* React Native version: 0.59.10
* react-native-linkedin version: 1.3.2
* Platform(s) (iOS, Android, or both?): both, iOS fine - Android issue

**Comment by aliiqbal436** [comment]
I am facing the same issue. @patrikwork1 had you fixed it?

**Comment by ShahilMangroliya** [comment]
I am also facing the same issue.
