### ISSUE TITLE
Webview Cache or Cookies

### ISSUE THREAD

**Issue by chayancbnits** [xcarpentier/react-native-linkedin#146]
I'm on expo SDK 36. And can't clear webview cache or cookies. I am using react-native-linkedin v 2.1.1 and WebView version 7.0.5.

**Comment by mainakCbnits** [comment]
I'm having the same issue.

I am too using expo sdk 36.

When I installed **react-native-linkedin** where I was installed webview already to the latest, it's occurring an error,  **RCTWebview multiple**, so after many hours spent I finally fixed that by downgrading **webview to v7.0.5**. 

But now in linkinmodal, suppose I've opened the modal and entering credential, 2nd time the modal doesn't open, it's taking the data from cookies or cache from webview of the previous state.

So how do I clear the cookies or cache of webview.

**Comment by chayancbnits** [comment]
> I'm having the same issue.
> 
> I am too using expo sdk 36.
> 
> When I installed **react-native-linkedin** where I was installed webview already to the latest, it's occurring an error, **RCTWebview multiple**, so after many hours spent I finally fixed that by downgrading **webview to v7.0.5**.
> 
> But now in **react-native-linkedin**, suppose I've opened the webview modal and entering credential, 2nd time the modal doesn't open, it's taking the data from cookies or cache from webview of the previous state.
> 
> So how do I clear the cookies or cache of webview.

same

**Comment by mainakCbnits** [comment]
hii @xcarpentier , can you please update the package.

**Comment by chayancbnits** [comment]
@mainakCbnits Thanks

**Comment by denis-babylone** [comment]
Is it possible to make "incognito" value configurable? It could be useful to don't open the form each time...
