### ISSUE TITLE
I'm not able to logout properly

### ISSUE THREAD

**Issue by VladimirHumeniuk** [xcarpentier/react-native-linkedin#147]
I saw manual how to log out from LinkedIn, and I did it in the same way as in package readme, but when I click "login" again, it's didn't ask for an email/password again, and just automatically logged me in. Is it possible to mark token as expired on logout, so the user will have to enter his credentials again after logout?

**Comment by DomVinyard** [comment]
heya, did this get resolved?  I am having this same problem

**Comment by namansukhwani** [comment]
Did anyone found a solution for logout its giving me this errors 
` [TypeError: null is not an object (evaluating '_this2.linkedinModal.logoutAsync')]`
linkedinModal is my ref.
