### ISSUE TITLE
Locked react-native-webview dependency version

### ISSUE THREAD

**Issue by fvsch** [xcarpentier/react-native-linkedin#149]
#### Issue Description

The `react-native-linkedin` package is requesting precise dependency versions:

```
"dependencies": {
  "query-string": "6.8.3",
  "ramda": "0.26.1",
  "uuid": "3.3.3",
  "react-native-webview": "7.0.5"
},
```

For native dependencies like `react-native-webview`, this forces projects using `react-native-linkedin` to use `react-native-webview@7.0.5`, even if it contains security issues or bugs that are since then fixed.

#### Steps to Reproduce / Code Snippets

1. Create a project that uses `react-native-webview` with a different version than `7.0.5`
2. `npm react-native-linkedin`
3. Try using the `LinkedInModal` component

Result:

> Invariant Violation: Tried to register two views with the same name RNCWebView

![](https://user-images.githubusercontent.com/243601/75570449-792f0280-5a57-11ea-9ef0-815be414b88a.png)

#### Expected Results

I expected `react-native-webview` to work at least with any `7.x` version of `react-native-webview`.

Would switching to a dependency scheme like `"react-native-webview": "^7.0.5"` be okay?
Version 8 seems to have very few breaking changes as well.

#### Additional Information

* Nodejs version: 12.16.1
* React version: 16.9.0
* React Native version: 0.61.5
* Expo version: n.a.
* react-native-linkedin version: 2.1.1
* Platform(s) (iOS, Android, or both?): both

**Comment by fvsch** [comment]
Note: #134 is similar but the resolution was "just use react-native-webview 7.0.5" (and clean the npm cache). This issue is about relaxing the dependency requirement.

**Comment by fvsch** [comment]
Given the diff in https://github.com/xcarpentier/react-native-linkedin/commit/8cbecb76b90a9b4a328cdccde48818f04341506c it looks like the `"react-native-webview": "7.0.5"` dependency was added to fix a TypeScript issue.

Would it work to move `"react-native-webview": "7.0.5"` to the `devDependencies` instead?

**Comment by kyleso** [comment]
There are some issues with `"react-native-webview" : "7.0.5"` regarding loading local files on Android that have since been fixed in new versions.

Relaxing the dependency seems like a good idea.

**Comment by denis-babylone** [comment]
@xcarpentier 
Any news about this please?

**Comment by jayeshgurudayalani** [comment]
facing same issue as shown in image but i am using react-native-instagram-login npm which uses different version of webview which causes this issue
can anyone help me

**Comment by Sterlingryan** [comment]
Did anyone of you find a fix for this ?

**Comment by shivani2911** [comment]
Does anyone get a solution? I faced the same issue
