### ISSUE TITLE
onSuccess doesn't return any data

### ISSUE THREAD

**Issue by ahgarni** [xcarpentier/react-native-linkedin#15]
onSuccess seems not working properly in version 1.0.30. it doesn't return token at all. and tested the onError and no error was raised. 

however, I tried to downgrade to 1.0.29 and 1.0.28 and when I did, I've got an error that says: 

`One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.
`

react: 16.0.0-alpha.12,
react-native": ^0.46.4,
expo:  20.0.1

**Comment by xcarpentier** [comment]
Could you please test again with the last one?
