### ISSUE TITLE
Asking for the LinkedIn login credentials in Web view browser every time.

### ISSUE THREAD

**Issue by ArvindKer90** [xcarpentier/react-native-linkedin#156]
Hi Team,
We are using your (this) library SDK for our Linkedin Authentication integration in our React native mobile app. 
We are able to integrate it successfully but it is asking for the linkedin login credentials in Web view browser every time even after we have already authenticated. 
Is there a way to set it up so that the user only enters it once or maybe once every month or does it have to be entered every single time?

**Comment by xcarpentier** [comment]
Hi,
WebView do not keep sessions cookies and the access token you get come with an expiration time stamp, you would be able to check this expiration and not showing this WebView until then.
Thanks

**Comment by Android-Dheeraj** [comment]
Hopefully 
this.linkedRef.current.logout() will resolve your issue.
