### ISSUE TITLE
onSuccess not called, when canceling on first try and then trying again

### ISSUE THREAD

**Issue by chitrangsinghvi** [xcarpentier/react-native-linkedin#16]
Hii @xcarpentier , 
First of all great work.
I went through the source code, I found that you are setting `raceCondition` true before error or success from linkedin occurs, and raceCondition is never reset, which blocks onSuccess to be called.

How to reproduce - 
1. Click on the cancel button in the modal
2. Trying signing in again
3. onSuccess is never called

**Comment by chitrangsinghvi** [comment]
@xcarpentier I think we can recreate `authState` every time `modalVisible` changes, and reset `raceCondition`.
I will give it a try and create a pull request once I found success.

**Comment by xcarpentier** [comment]
Available in v1.1.0
