### ISSUE TITLE
requireNativeComponent: "RNCWebView" was not found in the UIManager

### ISSUE THREAD

**Issue by smilydronavalli** [xcarpentier/react-native-linkedin#161]
Hi,

I got the above error after installed everything.

Kindly guide me

Thanks Inadvance

**Comment by krakzk** [comment]
Please make sure you have react-native-webview installed.
If you have latest RN, please make sure the webview has been linked correctly, else please link it by updating the settings.gradle, app/build.gradle and MainApplication.java manually. Or you can use command react-native link react-native-webview
