### ISSUE TITLE
Linked Closes automatically

### ISSUE THREAD

**Issue by srinivasanBG** [xcarpentier/react-native-linkedin#163]
#### Issue Description

LinkedIn modal closes automatically

#### Steps to Reproduce / Code Snippets

1.Open the linkedin
2.Closes automatically

#### Expected Results

It should not closes automatically

#### Additional Information

* Nodejs version: 10.16
* React version: 16.8.6
* React Native version: 0.60.5
* Expo version: Am using React native CLI
* react-native-linkedin version: 2.1.1
* Platform(s) (iOS, Android, or both?): Android and IOS

**Comment by srinivasanBG** [comment]
Please share some solution.

**Comment by rajngarg** [comment]
I am also having the same problem any solutions?

**Comment by srinivasanBG** [comment]
> I am also having the same problem any solutions?
