### ISSUE TITLE
renderButton isn't working

### ISSUE THREAD

**Issue by whitestranger7** [xcarpentier/react-native-linkedin#164]
I've tried to create a custom button using renderButton method. I found that all renderButton method is wrapper by TouchableHighlight with function to open the modal. But it's not working at all. So I've tried this

```
return (
    <LinkedInModal
      clientID="..."
      clientSecret="..."
      redirectUri="..."
      onSuccess={(token) => console.log(token)}
      renderButton={() => <Text>Sign in with LinkedIn</Text>}
    />
 );
```

Then I've got just text, which is open modal by clicking on it. But the thing is, that the text I wrapped isn't open a modal. What's the problem then?

* React version: 16.11.0
* React Native version: 0.62.2
* react-native-linkedin version: 2.1.1
* Platform(s) (iOS, Android, or both?): IOS

**Comment by whitestranger7** [comment]
The actual problem is here:
<img width="958" alt="Screen Shot 2020-08-18 at 19 06 43" src="https://user-images.githubusercontent.com/36364993/90542893-7d79e400-e18d-11ea-9bdf-e7e2289de31d.png">

<img width="840" alt="Screen Shot 2020-08-18 at 18 37 32" src="https://user-images.githubusercontent.com/36364993/90542882-79e65d00-e18d-11ea-9b24-b2b68899a4a6.png">

On master branch in .ts file you're wrapping all renderButton with TouchableOpacity, but in node_modules there's no such wrapper, that's the problem

**Comment by whitestranger7** [comment]
UPD:

This is working solution

```
const LinkedInButton = ({ ...props }) => {
  const modalRef = useRef();

  return (
    <LinkedInModal
      ref={modalRef}
      clientID="..."
      clientSecret="..."
      redirectUri="..."
      onSuccess={props.onSuccess}
      renderButton={() => (
        <CustomButton
          {...props}
          onPress={() => modalRef.current && modalRef.current.open()}>
          Sign in with LinkedIn
        </CustomButton>
      )}
    />
  );
};
```

**Comment by Daniel-Griffiths** [comment]
Thanks for posting the solution @whitestranger7 

This is a well timed issue :smile:
