### ISSUE TITLE
Error: "RNCWebView" was not found in the UIManager 

### ISSUE THREAD

**Issue by ShashwatMDas** [xcarpentier/react-native-linkedin#166]
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets
....
return (
    <LinkedInModal
      clientID="..."
      clientSecret="..."
      redirectUri="..."
      onSuccess={(token) => console.log(token)}
      renderButton={() => <LinkedInButton />}
    />
 );
.....

const LinkedInButton = ({ ...props }) => {
  const modalRef = React.useRef();

  return (
    <LinkedInModal
      ref={modalRef}
      clientID="..."
      clientSecret="..."
      redirectUri="..."
      onSuccess={props.onSuccess}
      renderButton={() => (
        <CustomButton
          {...props}
          onPress={() => modalRef.current && modalRef.current.open()}>
          Sign in with LinkedIn
        </CustomButton>
      )}
    />
  );
};

[FILL THIS OUT]

#### Expected Results
The modal for linkedin login should open. But I get the error- requireNativeComponent: "RNCWebView" was not found in the UIManager

[FILL THIS OUT]

#### Additional Information

* Nodejs version: 12.16.3
* React version: 
* React Native version: 0.62.2
* Expo version: {React Native CLI}
* react-native-linkedin version: 2.1.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by castor55** [comment]
@ShashwatMDas I see the same issue. Why is this issue closed with out any solution?
