### ISSUE TITLE
Error on various occasions

### ISSUE THREAD

**Issue by ShashwatMDas** [xcarpentier/react-native-linkedin#167]
#### Issue Description

The package is working properly, gets the token and everything, but the issue is, it throws an error, which upon closing works just as expected. The issue is the error, which will make the app crash in production. 
1) Upon Clicking the button, the modal open, and as soon as the form of linkedin loads, the error screen comes.
2) Dismiss the error, the form is right there properly, fill the details and click sign in. The same error comes again.
3) Dismiss the error, modal is still there, give permissions, the token comes back properly, but again as soon as the token comes, same error comes. Dismiss again and everything works properly thereafter.

#### Steps to Reproduce / Code Snippets
```

import React from 'react'
import { StyleSheet, View, Text, Dimensions } from 'react-native'
import { TextInput, configureFonts, DefaultTheme, Provider as PaperProvider } from 'react-native-paper';
import { Container, Header, Content, Form, Item, Input, Label, H1, H2, H3, Icon, Button, Segment, Thumbnail } from 'native-base';
import LinkedInModal from 'react-native-linkedin'
 var height = Dimensions.get('screen').height;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
})
 
export default class LinkedIn extends React.Component {
  render() {
  const linkedRef = React.createRef();
    return (
        <LinkedInModal
            clientID="xxx"
            ref={linkedRef}
            clientSecret="xxx
            redirectUri="xxx
            onSuccess={(token) => console.log(token)}
            renderButton={() => 
            (
                <Button block style={{backgroundColor: "#fff", marginVertical: 15, height: 60, marginTop: height*0.03, flexDirection: 'row'}} onPress={() => linkedRef.current && linkedRef.current.open()}>
                    <Thumbnail source={require('../assets/linkedin.jpg')} style={{height: 35, width: 35}} />
                    <Text style={{color: "#000", fontSize: 20}}>  LinkedIn</Text>
                </Button>
            )
            }
            onError ={(err) => console.log(err)}
            />
    );
  }
}
```
#### Expected Results

The token comes without these error. Error is the same everytime:
`Invariant Violation: Module  is not a registered callable module (calling onShouldStartLoadWithRequest)`

![WhatsApp Image 2020-09-10 at 4 33 53 AM](https://user-images.githubusercontent.com/43996845/92663552-3f508a00-f31f-11ea-853b-f8e33531edc2.jpeg)

#### Additional Information

* Nodejs version: 12.16.3
* React version: [FILL THIS OUT]
* React Native version: 0.62.2
* Expo version: {React Native Cli}
* react-native-linkedin version: 2.1.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by ali14N** [comment]
@xcarpentier facing multiple issues like this. Is npm module in sync with the repo? Please confirm

**Comment by shivani2911** [comment]
same is is there any solution ?

**Comment by rahulson** [comment]
@ShashwatMDas 
Facing same issue
I set react-native-webview version to 10.8.2 and it works fine now

**Comment by shivani2911** [comment]
it's working perfectly now thanks

**Comment by rayWille** [comment]
Thanks @rahulson 
It is working fine now

**Comment by joaocarlospf** [comment]
v10.8.2 does not solves for me..
