### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCWebView old webview package

### ISSUE THREAD

**Issue by crcnum4** [xcarpentier/react-native-linkedin#168]
#### Issue Description
When starting app error occurs with the message:
Invariant Violation: Tried to register two views with the same name RNCWebView

#### Steps to Reproduce / Code Snippets

Start the APP

#### Expected Results

App should start and use the most recent React-Native-webview

#### Additional Information

My research tells me the issue is with the version number on the webview. Expo SDK 39 is now using react-native-webview 10.7.0 and React-native-linkedin is still using 7.0.5
when i change my main app to use 7.0.5 the app will load but when i attempt to use the modal i get an error that currentlyFocusedField is deprecated and should update to currentlyFocusedInput. 

it seems the fix for this would be to simply have this package start using react-native-webview 10.7.0

* Nodejs version: 12.
* React version: 16.13.1
* React Native version: expo sdk 39
* Expo version: 39
* react-native-linkedin version:  2.1.1
* Platform(s) (iOS, Android, or both?): iOS (not yet tested on android)

**Comment by crcnum4** [comment]
i may try to look at this myself and see if I can update your package. but any help with this would be appreciated.

**Comment by AlexanderKaraschuk** [comment]
Hi, @crcnum4, I am facing the same issue. Updating packeage.json dependencies are the solution to this issue?

**Comment by crcnum4** [comment]
My testing seems to point to this heavily as well as reports from other expo users. I actually tried to fork this but i couldn't figure out how to make this item runnable on my app as an import with the build processes that this package has.
what I have done though is recreated a very basic version of this item borrowing the styling and layout of some of the items. So far I seem to have almost identical functionality in this minimal component i created which confirms for me the big issue here is the outdated webview package

**Comment by crcnum4** [comment]
here's a link to a gist of the LinkedInModal i created that is heavily influenced by this package

https://gist.github.com/crcnum4/3e8a8e4ddc1b8186d3d5f7fe7ebb0f11

it shows i can have the functionality i want from this package as long as i have the most recent webview package.
