### ISSUE TITLE
Invariant Violation: Module is not a registered callable module (calling onShouldStartLoadWithRequest)

### ISSUE THREAD

**Issue by SanjanaTailor** [xcarpentier/react-native-linkedin#171]
Hello, 

I am facing this issue after opening linkedin URL in webView. 

can you please suggest some resolution for same.

**Comment by Tanyanka** [comment]
Hi @SanjanaTailor I am facing the same issue

**Comment by Tanyanka** [comment]
rollback react-native-webview to 9.0.2 version solves the problem

**Comment by m7amad-7asan** [comment]
rollback to react-native-webview@10.3.2 to solve this

**Comment by SanjanaTailor** [comment]
> Hi @SanjanaTailor I am facing the same issue

Hi you can use version 8.3.1 or 10.3.2 to resolve this issue, thank you

**Comment by DomVinyard** [comment]
I am unable to confirm that rolling back solves this problem. No luck for me

**Comment by jasimawan** [comment]
react-native-webview: 11.0.0 worked for me.
