### ISSUE TITLE
Prop 'areaTouchText' not working

### ISSUE THREAD

**Issue by bewakes** [xcarpentier/react-native-linkedin#172]
I could not style the text inside this component. The documentation says `areaTouchText`  but it is not working. 

Am I missing anything?

**Comment by mensonones** [comment]
Hi, @bewakes! I created this property. The version of lib in npm is not updated with the most recent changes. I recommend that you compile the lib on your machine, so that you can enjoy it more up to date.

**Comment by bewakes** [comment]
Thanks for letting me know. Are you not maintaining this anymore?

**Comment by mensonones** [comment]
Hi, @bewakes! I only contribute to the property in question. The creator is the @xcarpentier :)

**Comment by bewakes** [comment]
Ah, yes. I see. :)
