### ISSUE TITLE
Invariant violation: Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by rayasrahiman** [xcarpentier/react-native-linkedin#175]
![272CB934-C7F6-414D-A939-6D0CF11137BD](https://user-images.githubusercontent.com/58700409/101899392-c25dd680-3bd3-11eb-8018-594e966aa49d.jpeg)
#### Issue Description

I'm getting this error while running my expo app after LinkedIn package installation

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

After the JavaScript bundle enter into login page

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* Expo version: [FILL THIS OUT]
* react-native-linkedin version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by rayasrahiman** [comment]
> ![272CB934-C7F6-414D-A939-6D0CF11137BD](https://user-images.githubusercontent.com/58700409/101899392-c25dd680-3bd3-11eb-8018-594e966aa49d.jpeg)
> 
> #### Issue Description
> [FILL THIS OUT]
> 
> #### Steps to Reproduce / Code Snippets
> [FILL THIS OUT]
> 
> #### Expected Results
> [FILL THIS OUT]
> 
> #### Additional Information
> * Nodejs version: [FILL THIS OUT]
> * React version: [FILL THIS OUT]
> * React Native version: [FILL THIS OUT]
> * Expo version: [FILL THIS OUT]
> * react-native-linkedin version: [FILL THIS OUT]
> * Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

Using this package on react native expo tried to run the app after installing this LinkedIn package but I get this error.

**Comment by DanielSchwartz89** [comment]
Any possible fix or workaround for this?

**Comment by rayasrahiman** [comment]
yes we need to keep only one  RNCWebView package in the root node module
and DELETE  RNCWebView folder not uninstall from react-native-linkedin
package inside its node module. Clear Cache and then run the code.

**Comment by rafaismyname** [comment]
A workaround that worked for me is:
Add `"postinstall": "rm -rf ./node_modules/react-native-linkedin/node_modules/react-native-webview"` to your `scripts` in the `package.json` file.

**Comment by Daniel-Griffiths** [comment]
Nice one @rafaismyname. That work around worked for me. 🙂

**Comment by jaydips2020** [comment]
@rafaismyname  Its work Thanks).

**Comment by jaydips2020** [comment]
> A workaround that worked for me is:
> Add `"postinstall": "rm -rf ./node_modules/react-native-linkedin/node_modules/react-native-webview"` to your `scripts` in the `package.json` file.

It's work Thanks
