### ISSUE TITLE
Invalid client authentication failed after login and allow in LinkedinModel after login

### ISSUE THREAD

**Issue by SanjanaTailor** [xcarpentier/react-native-linkedin#177]
![err](https://user-images.githubusercontent.com/4736998/102494009-081a1380-409a-11eb-87a2-754c18334a0e.jpg)
<LinkedInModal
        ref={linkedRef}
        clientID="*********"
        clientSecret="***********"
        redirectUri="https://www.linkedin.com/myURL"
        linkText="Login with LinkedIn"
        onSuccess={(token) => console.log('token', token)}
      />
       ERROR    {
  "type": "invalid_client",
  "message": "Client authentication failed"
}
what is wrong here so getting this error clientID and clientSecret are same as developer account. Please suggest

**Comment by mensonones** [comment]
Did you configure your keys well on linkedin?

**Comment by SanjanaTailor** [comment]
@mensonones Attached screenshot for below, please inform me any other information required 
![Capture](https://user-images.githubusercontent.com/4736998/102746571-8b7e8200-4384-11eb-908c-b7c7b77dc3f8.PNG)

**Comment by mensonones** [comment]
Hi, @SanjanaTailor! It seems to be all right. You could follow the tutorial I created. Maybe it will help you or you could show me your code for better analysis.

Tutorial: https://dev.to/mensonones/login-com-linkedin-usando-react-native-288n

**Comment by SanjanaTailor** [comment]
Thank you @mensonones. I will check it.

**Comment by SanjanaTailor** [comment]
@mensonones, I am getting still same error.

**Comment by mensonones** [comment]
Hi, @SanjanaTailor! We can close this issue?

**Comment by SanjanaTailor** [comment]
resolved and closing an issue
