### ISSUE TITLE
Invariant Violation:

### ISSUE THREAD

**Issue by Muthu011** [xcarpentier/react-native-linkedin#180]
#### Issue Description

Invariant Violation: Module  is not a registered callable module (calling onShouldStartLoadWithRequest). A frequent cause of the error is that the application 
entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

#### Steps to Reproduce / Code Snippets

When clicking login with linkedIn button

#### Expected Results

Error should not come 

[FILL THIS OUT]

#### Additional Information

* Nodejs version: [14.15.5]
* React version: [17.0.3]
* React Native version: [0.64.2]
* Expo version: [FILL THIS OUT] using react native CLI
* react-native-linkedin version: [2.1.1]
* Platform(s) (iOS, Android, or both?): [Android for now]

**Comment by zuzabrzozowska** [comment]
Any update on this one? It shows only on Android device for me
