### ISSUE TITLE
Custom renderButton doesn't have TouchableOpacity wrapper on the renderButton

### ISSUE THREAD

**Issue by rahul-mahato** [xcarpentier/react-native-linkedin#188]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-linkedin@2.1.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-linkedin/lib/index.js b/node_modules/react-native-linkedin/lib/index.js
index ae6fd22..c4a1658 100644
--- a/node_modules/react-native-linkedin/lib/index.js
+++ b/node_modules/react-native-linkedin/lib/index.js
@@ -154,7 +154,9 @@ export default class LinkedInModal extends React.Component {
         this.renderButton = () => {
             const { renderButton, linkText } = this.props;
             if (renderButton) {
-                return renderButton();
+                return (React.createElement(TouchableOpacity, { accessibilityComponentType: 'button', accessibilityTraits: ['button'], onPress: this.open },
+                renderButton()))
+                
             }
             return (React.createElement(TouchableOpacity, { accessibilityComponentType: 'button', accessibilityTraits: ['button'], onPress: this.open },
                 React.createElement(Text, null, linkText)));
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by NazimMertBilgi** [comment]
<LinkedInModal
                      ref={ref => {
                        this.linkedinModalRef = ref
                      }}
                      shouldGetAccessToken={false}
                      clientSecret={null}
                      clientID={LINKEDIN_CLIENT_ID}
                      redirectUri="https://investsize.com"
                      onSuccess={token => console.log(token)}
                      renderButton={() => <TouchableOpacity onPress={() => this.linkedinModalRef.setState({modalVisible: true})}>
                        <Image source={linkedinIcon} style={styles.socialMediaIconLinkedin}></Image>
                      </TouchableOpacity>}
                    />
