### ISSUE TITLE
Callback is not called on first time

### ISSUE THREAD

**Issue by Nodonisko** [xcarpentier/react-native-linkedin#30]
After success login nothing happen, no error, no success callback.  On second click is success callack fired immediately after click.

**Comment by xcarpentier** [comment]
Hello @Nodonisko,
Could you please provide the context of the error ?
Code source, platform... (android or ios, ...)
Thanks!

**Comment by Nodonisko** [comment]
Tested only on iOS, React Native 0.45.1
1. Click on Login to LinkedIn
2. Fill inputs and success login to LinkedIn
3. Popup disappear, but nothing happen, no callback, no error
4. Click again to Login to LinkedIn
5. Popup appear and callback with access_token is immediately called
6. Now you can close popup with close button, without filling credentials

**Comment by Nodonisko** [comment]
Update... callback is fired after next touch anywhere in app, is not necessary to open popup again.

**Comment by Nodonisko** [comment]
Finally found where the problem is... `await response.json()` => https://github.com/facebook/react-native/issues/6679

**Comment by xcarpentier** [comment]
Is this an error in the react-native-linkedin or on your side ?

**Comment by xcarpentier** [comment]
Dou you mean that:
https://github.com/xcarpentier/react-native-linkedin/blob/master/index.js#L130

**Comment by Nodonisko** [comment]
Yes this line... You should add only note do README or let this issue open, it's not problem of your library but of RN itself. It should work correctly in production envirovent and RN 0.47+

**Comment by cablegunmaster** [comment]
Can there also be a test on Android?
