### ISSUE TITLE
Possibility to have an event fired when you fetch the token

### ISSUE THREAD

**Issue by Softcadbury** [xcarpentier/react-native-linkedin#44]
Hello,

Could we have an event fire when the user validate his credential ?
Because when this happens, the modal close and it can take some time before the success/error event is fire and I would like to display a loading to the user during this time.

After a look to your source, I think that the event could be fired just before the call to fetchToken.

What do you think? I can help on a PR. Thanks :)

**Comment by xcarpentier** [comment]
Hello, 
It’s a good idea...
Yes PR it 😉

**Comment by Softcadbury** [comment]
Here it is: https://github.com/xcarpentier/react-native-linkedin/pull/45
I choose to name the function onSignIn, let me know what you think.
