### ISSUE TITLE
How to get the basic profile of a user after getting the token?

### ISSUE THREAD

**Issue by kk1429** [xcarpentier/react-native-linkedin#48]
I am trying to get the basic profile of a user after he/she has logged in through linkedin in the onSuccess function.

This is how I am trying to accomplish it:- 
```
      <LinkedInModal
                                ref={ (linkedInModal) => {
                                    this.linkedinButton = linkedInModal;
                                }}
                                permissions={['r_basicprofile', 'r_emailaddress', 'rw_company_admin', 'w_share']}
                                clientID="secret"
                                clientSecret="secret"
                                redirectUri="secret"
                                renderButton={this.renderLinkedInButton.bind(this)}
                                onSuccess={
                                    token => {
                                        console.log(token);
                                        axios
                                        .get('https://api.linkedin.com/v1/people/~?format=json')
                                        .then(user => console.log(user))
                                        .catch(error => console.log(error));
                                    }
                                }
                                onSignIn={user => console.log(user)}
                            />
```

I am able to get the token but the get results in a 401 Error. Any idea? I think I am doing something wrong. :/

**Comment by saimemre** [comment]
Solve this? @kk1429

**Comment by xcarpentier** [comment]
cc @saimemre & @kk1429 

You miss access_token.

I extract a piece of my code to help you (will copy it in README): 
```javascript
const baseApi = 'https://api.linkedin.com/v1/people/'
      const params = [
        'first-name',
        'last-name',
      ]
      const qs = {
        format: 'json',
        oauth2_access_token: access_token,
      }

      const response = await fetch(
        `${baseApi}~:(${params.join(',')})?${querystring.stringify(qs)}`,
      )
      const payload = await response.json()
```

**Comment by saimemre** [comment]
@kk1429 I make this;

'Authorization': 'Bearer ' + access_token

**Comment by saimemre** [comment]
@xcarpentier @kk1429  
I make this;

`const responseData = await fetch(
                    "https://api.linkedin.com/v1/people/~:(first-name,last-name,positions)?format=json",
                    {
                      method: 'GET',
                      headers: {
                        'Authorization': 'Bearer ' + access_token
                      }
                    }
                  );`

Thanks for package @xcarpentier

**Comment by xcarpentier** [comment]
@saimemre yes it's better in header than query string, will change the readme ;)

**Comment by DavitVosk** [comment]
Hi @xcarpentier. Thanks for your created package. 
My problem is here: I could not find which kind of data we can retrieve from Linkedin and hence what params we should pass. By the way 'picture-urls::(original)' passed param does not return my picture in Linkedin. Also we need to get user id in Linkedin to arrange proper registration of the customer for this or that kind of application. 

Thanks in advance.
