### ISSUE TITLE
Modal cannot be closed after pressing Cancel button on iOS

### ISSUE THREAD

**Issue by danielrys** [xcarpentier/react-native-linkedin#56]
Hi,

I am currently facing a problem with the `Cancel` button. When it's pressed, the behavior on android is correct (the modal is closed), but on iOS, the modal stays open and the webview is redirected to `redirectUri`. Also, the modal cannot be closed when this happens (the close button in the corner is visible but stops working).

There is no `onClose` handler implemented and `onError` is used just for firing an alert, so it should not cause any trouble. Any ideas?

[Video link](https://drive.google.com/file/d/10JJlzRIqbqQsJ329cKnT-0SnmwYZz9GJ/view?usp=sharing)

RN version: `0.45.1`

**Comment by xcarpentier** [comment]
Hi,

You can't use `onError` props?
https://github.com/xcarpentier/react-native-linkedin#props

**Comment by danielrys** [comment]
There is no problem in `onError`, I was just trying to say that I do not have any special handlers bound to it.

**Comment by xcarpentier** [comment]
Do you mean it should not log error by default right?

**Comment by xcarpentier** [comment]
I think I can fix your error just by adding a test like that `if(__DEV__){ ... }`
https://github.com/xcarpentier/react-native-linkedin/blob/e7cefbe6da8d56d29201da8308e5bbd87e8e8917/index.js#L134

What do you think?

**Comment by danielrys** [comment]
No no, the `onError` part is unimportant. The problem Is in the redirect, as you can see in the video - the modal displays the website instead of being closed. After the redirect, the modal cannot be closed at all.

**Comment by xcarpentier** [comment]
Yes but I think this is due to the console.error ... if you override like `onError={()=>{}}` is that fix your redirect to website bug?

**Comment by xcarpentier** [comment]
Did you test with `onError={()=>{}}`?

**Comment by danielrys** [comment]
Sorry for the delay - just tested and it seems to fix the problem, but is there any way to have an `onError` handler and prevent this behavior?

**Comment by xcarpentier** [comment]
Yes I will define this default nop function when `__DEV__ === false` in next release.
