### ISSUE TITLE
use my own button

### ISSUE THREAD

**Issue by jslz** [xcarpentier/react-native-linkedin#63]
#### Issue Description

hi, I'd like to be able to present the LinkedInModal after my own button widget gets a press. The way my code works, the button I am passing in to the LIM ends up fighting over the onPress with the LinkedInModal. So I'd like the option of being able to cause LIM to just appear w/out it doing anything to manage any button.

if that makes any sense.

#### Steps to Reproduce / Code Snippets

not much to show since i want to do something that afaict isn't supported :-)

#### Expected Results

see description above.

#### Additional Information

* Nodejs version: v6.11.1
* React version: n/a
* React Native version: 0.51.0
* Expo version: n/a
* react-native-linkedin version: 1.3.1
* Platform(s) (iOS, Android, or both?): both

**Comment by xcarpentier** [comment]
Hello, 
it’s already possible: 
https://github.com/xcarpentier/react-native-linkedin/blob/21f86a60d42a15eff6b326069d77aac079fee27f/example/App.js#L121

**Comment by jslz** [comment]
thanks!

**Comment by macscripter** [comment]
Maybe it's better to include a prop like "openImmediately" or something like that to go to the linkedin form without passing through "linkText". Or, much better, if the linkText = null --> go directly to the linkedin form.
