### ISSUE TITLE
Authenticate using linkedin app if already installed and running

### ISSUE THREAD

**Issue by botmane** [xcarpentier/react-native-linkedin#64]
Hello,

Is there any way to use your module without typing the linkedin password ? if the LinkedIn app is already installed. 

Here's an app that implements it seemlesly: www.shapr.co

Thanks

**Comment by xcarpentier** [comment]
It should be possible to get cookies from external connexion with WebBrowser into expo, but for now I'm using webview.

Do you think WebBrowser implementation (ie. in expo) can give you what you're looking for?

**Comment by oriharel** [comment]
@botmane @xcarpentier a MUST capability. No one actually remembers their LinkedIn credentials which mean this package can't be used...
