### ISSUE TITLE
Invalid access token

### ISSUE THREAD

**Issue by timscott** [xcarpentier/react-native-linkedin#80]
I enter my credentials, and I get back an `access_token` and `expires_in`. But when I try to use the token, I get "Invalid access token". I tried API v1 and got the same error.

```bash
> curl -X GET \
>   'https://api.linkedin.com/v2/connections?q=viewer&count=50' \
>   -H 'Authorization: Bearer [token returned by onSuccess]' \
>   -H 'Connection: Keep-Alive' \
>   -H 'Host: api.linkedin.com'

{"serviceErrorCode":65600,"message":"Invalid access token","status":401}
```

This seems to be exactly as the documentation shows. Also, I verified [in my linked in permitted services](https://www.linkedin.com/psettings/permitted-services) that the app is authorized. What could be wrong?

* React version: 16.3.0-alpha.1
* React Native version: 0.54.4
* react-native-linkedin version: 1.3.1
* Platform(s) (iOS, Android, or both?): both

**Comment by xcarpentier** [comment]
Hi,
Which permissions did you specified into token request?

**Comment by timscott** [comment]
It seems that LinkedIn requires applying even for `r_basicprofile`. Oh well, it was a nice idea. 😁
