### ISSUE TITLE
Error: Unable to resolve data for blob: (null)

### ISSUE THREAD

**Issue by BenCook28** [xcarpentier/react-native-linkedin#86]
#### Issue Description

First of all, thanks for building this package since signup and signin with LinkedIn are top priorities for me.  On an iOS simulator, I get the error below in my console after I press Login with LinkedIn:

Error: Unable to resolve data for blob: (null)
    at createErrorFromErrorData (blob:http://localhost:8081/d38dac0a-7b3a-40b4-80ae-bc0701c33550:2056:17)
    at blob:http://localhost:8081/d38dac0a-7b3a-40b4-80ae-bc0701c33550:2008:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/d38dac0a-7b3a-40b4-80ae-bc0701c33550:2450:18)
    at blob:http://localhost:8081/d38dac0a-7b3a-40b4-80ae-bc0701c33550:2195:18
    at MessageQueue.__guardSafe (blob:http://localhost:8081/d38dac0a-7b3a-40b4-80ae-bc0701c33550:2363:11)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/d38dac0a-7b3a-40b4-80ae-bc0701c33550:2194:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:70:58

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

I tried the code below, except with my clientID and clientSecret

`import React, { Component } from "react";
import {
  Text,
  View,
  Image,
  TouchableHighlight
} from "react-native";
import { connect } from "react-redux";
import PropTypes from "prop-types";
import Icon from "react-native-vector-icons/FontAwesome";
import { withNavigation } from "react-navigation";
import { signInWithFacebook, signInWithGoogle } from "../../Redux/Actions/Auth";
import LinkedInModal from 'react-native-linkedin'
import { Divider } from "../Utilities";

import { Register as styles } from "../Styles";

class Register extends Component {
  static propTypes = {
    signInWithFacebook: PropTypes.func,
    signInWithGoogle: PropTypes.func,
    isLoggedIn: PropTypes.bool
  };

  constructor() {
    super();
  }

  onSuccess = ({ exists, user }) => {
    if (exists) Actions.register();
    else Actions.phoneNumber({ user });
  }

  onError = (error) => {
    alert(error.message);
  }

  async getUser({ access_token }) {
    const baseApi = 'https://api.linkedin.com/v1/people/'
    const qs = { format: 'json' }
    const params = [
      'first-name',
      'last-name',
      'picture-urls::(original)',
      'headline',
      'email-address',
    ]

    const response = await fetch(`${baseApi}~:(${params.join(',')})?format=json`, {
      method: 'GET',
      headers: {
        Authorization: 'Bearer ' + access_token,
      },
    })
    const payload = await response.json()
    console.log('payload is ', payload);
  }

  render() {
    return (
      <View style={styles.container}>
        <Image
          style={styles.logo}
          source={require("../../Images/logo.png")}
          resizeMode="contain"
        />
        <Text style={styles.tagline}>Connect. Compete. Play.</Text>

        <LinkedInModal
          clientID="//my clientId"
          clientSecret="//my clientSecret"
          redirectUri="http://localhost:3000/auth/linkedin"
          onSuccess={token => {
            this.getUser(token)
          }
          }
        />
        <View style={styles.socialButtons}>

          <Divider />

          <Icon.Button
            name="user"
            backgroundColor="#051836"
            onPress={e => this.props.navigation.navigate("LocalRegister")}
            {...iconStyles}
          >
            <Text style={styles.socialRegisterTextEmail}>
              Sign up with Email
            </Text>
          </Icon.Button>
          <Divider />
          <View style={styles.registerLinkContainer}>
            <TouchableHighlight
              onPress={() => {
                this.props.navigation.navigate("Login");
              }}
            >
              <Text style={styles.registerLink}>
                Already on Groop?{" "}
                <Text style={styles.registerSignInLink}>Sign in.</Text>
              </Text>
            </TouchableHighlight>
          </View>
        </View>
      </View>
    );
  }
}

const iconStyles = {
  borderRadius: 3,
  iconStyle: { paddingVertical: 7, paddingLeft: 5 }
};

const mapStateToProps = (state) => {
  return {
    isLoggedIn: state.auth.isLoggedIn
  };
};

const mapDispatchToProps = dispatch => {
  return {
    signInWithFacebook: (token, successCB, errorCB) => {
      dispatch(signInWithFacebook(token, successCB, errorCB));
    },
    signInWithGoogle: (token, successCB, errorCB) => {
      dispatch(signInWithGoogle(token, successCB, errorCB));
    }
  };
};

export default withNavigation(
  connect(mapStateToProps, mapDispatchToProps)(Register)
);
`

[FILL THIS OUT]

#### Expected Results

I would see a console log of profile details, like I did on an empty project

[FILL THIS OUT]

#### Additional Information

* Nodejs version: 8.9.4
* React version: 16.3.2
* React Native version: 0.55.2
* Expo version: 25.0.0
* react-native-linkedin version: 1.3.1
* Platform(s) (iOS, Android, or both?): iOS

**Comment by maxbeech** [comment]
Did you ever resolve this issue @BenCook28? Having a similar thing. Cheers!
