### ISSUE TITLE
Logout from LinkedIn

### ISSUE THREAD

**Issue by AgNm** [xcarpentier/react-native-linkedin#89]
I am successfully able to login on linkedIn. How can I logout from it?

**Comment by tannera** [comment]
It doesn't seem to be implemented yet, even though it's a necessary function.

**Comment by xcarpentier** [comment]
This lib is much more a way to get access token than call linkedin api. So yes logout in an app is necessary but you can do it by yourself just by calling linkedin API.

**Comment by AkshitSahani** [comment]
Was anyone able to figure out a way to logout of linkedIn?

**Comment by neoketan** [comment]
tried to clear cookies by react-native-linkedin package but still it is managing session
